### ISSUE TITLE
Network Not Available

### ISSUE THREAD

**Issue by pareta2** [ArunYogi/paytm-cordova-plugin#5]
Hello
I have implemented cordova plugin but on executing the code i am getting below error "Network Not Available"
RESPCODE: 501
RESPMSG: "Network Not Available"
STATUS: "TXN_FAILURE"

**Comment by ArunYogi** [comment]
I faced the"Network Not Available" issue when I didnt pass "ENVIRONMENT" value. The issue was resolved after passing that value to paytm

**Comment by UTSOURCE** [comment]
@ArunYogi @pareta2 I have the same problem, but you said "ENVIRONMENT" I still don't know how to pass the value, can you give me an example?

**Comment by ArunYogi** [comment]
For non-production environment, sample option to be send 
`{
  "REQUEST_TYPE": "DEFAULT",
  "MID": "PAYTM_MERCHANT_ID",
  "ORDER_ID": "ORDER0000000001",
  "CUST_ID": "10000988111",
  "INDUSTRY_TYPE_ID": "PAYTM_INDUSTRY_TYPE_ID",
  "CHANNEL_ID": "WAP",
  "TXN_AMOUNT": "1",
  "WEBSITE": "PAYTM_WEBSITE",
  "CALLBACK_URL": "https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=ORDER0000000001",
  "EMAIL": "abc@gmail.com",
  "MOBILE_NO": "9999999999",
"ENVIRONMENT": "staging",
  "CHECKSUMHASH": "w2QDRMgp1/BNdEnJEAPCIOmNgQvsi+BhpqijfM9KvFfRiPmGSt3Ddzw+oTaGCLneJwxFFq5mqTMwJXdQE2EzK4px2xruDqKZjHupz9yXev4="
}`


For Porduction environment, sample options to be send:
`{
  "REQUEST_TYPE": "DEFAULT",
  "MID": "PAYTM_MERCHANT_ID",
  "ORDER_ID": "ORDER0000000001",
  "CUST_ID": "10000988111",
  "INDUSTRY_TYPE_ID": "PAYTM_INDUSTRY_TYPE_ID",
  "CHANNEL_ID": "WAP",
  "TXN_AMOUNT": "1",
  "WEBSITE": "PAYTM_WEBSITE",
  "CALLBACK_URL": "https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=ORDER0000000001",
  "EMAIL": "abc@gmail.com",
  "MOBILE_NO": "9999999999",
"ENVIRONMENT": "production",
  "CHECKSUMHASH": "w2QDRMgp1/BNdEnJEAPCIOmNgQvsi+BhpqijfM9KvFfRiPmGSt3Ddzw+oTaGCLneJwxFFq5mqTMwJXdQE2EzK4px2xruDqKZjHupz9yXev4="
}`

**Comment by UTSOURCE** [comment]
@ArunYogi Thank you very much

**Comment by UTSOURCE** [comment]
@ArunYogi  {
          "REQUEST_TYPE": "DEFAULT",
          "MID": result.data.PaytimResult.dic.MID,
          "ORDER_ID": result.data.PaytimResult.dic.ORDER_ID,
          "CUST_ID": result.data.PaytimResult.dic.CUST_ID,
          "INDUSTRY_TYPE_ID": "Retail",
          "CHANNEL_ID": "WAP",
          "TXN_AMOUNT": result.data.PaytimResult.dic.TXN_AMOUNT,
          "WEBSITE": "APPSTAGING",
          "CALLBACK_URL": result.data.PaytimResult.paytmURL,
          "EMAIL": "raju@sibaecom.com",
          "MOBILE_NO": result.data.PaytimResult.dic.MOBILE_NO,
          "ENVIRONMENT": "staging",
          "CHECKSUMHASH": result.data.PaytimResult.dic.CHECKSUMHASH
        }
For non-production environment, option to be send
But there is an abnormal payment interface.
![image](https://user-images.githubusercontent.com/14830459/43989415-28b57436-9d7c-11e8-8f48-c32ce585cc9e.png)
Where should I check now?
![image](https://user-images.githubusercontent.com/14830459/43989461-fc8b88a4-9d7c-11e8-8811-0e4cacac060f.png)
CALLBACK_URL="https://securegw-stage.paytm.in/theia/processTransaction?orderid=UT8QYTMO6406_23078742-2e7c-4068-8118-394f138f8cbd"

**Comment by ArunYogi** [comment]
Ok, now we are getting somewhere, the screenshot is from Paytm. This is shown when information to PAytm is not recognised by them. It might be issue in data send by you, or some settings is not enabled for your MID. This has to be checked with them. 

Provide them the android logs from your app(output of `adb logcat`) while discussing about the issue.

**Comment by UTSOURCE** [comment]
@ArunYogi  adb logac:
08-11 08:16:17.717 8724-8818/ut.app D/PGSDK: Creating an instance of Paytm PG Service...
    Created a new instance of Paytm PG Service.
08-11 08:16:17.726 8724-8724/ut.app W/zygote: Attempt to remove non-JNI local reference, dumping thread
08-11 08:16:17.735 8724-8724/ut.app D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 7561 : [object Object]
08-11 08:16:17.735 8724-8724/ut.app I/chromium: [INFO:CONSOLE(7561)] "[object Object]", source: file:///android_asset/www/build/main.js (7561)
08-11 08:16:17.745 8724-8818/ut.app D/PGSDK: CUST_ID = 4567fghhn
08-11 08:16:17.746 8724-8818/ut.app D/PGSDK: MOBILE_NO = 7777777777
    CHANNEL_ID = WAP
08-11 08:16:17.748 8724-8818/ut.app D/PGSDK: ORDER_ID = UT8153LQ6407_ea2746da-e17d-4e8c-beb0-87cb7a22c467
08-11 08:16:17.749 8724-8818/ut.app D/PGSDK: TXN_AMOUNT = 2497.80
08-11 08:16:17.750 8724-8818/ut.app D/PGSDK: CALLBACK_URL = https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=UT8153LQ6407_ea2746da-e17d-4e8c-beb0-87cb7a22c467
    MID = dgqr@CJD0@UBhkWZ
    REQUEST_TYPE = DEFAULT
    INDUSTRY_TYPE_ID = Retail
    EMAIL = raju@sibaecom.com
    WEBSITE = APPSTAGING
    Starting the Service...
    
    --------- beginning of system
08-11 08:16:17.765 8724-8818/ut.app D/PGSDK: Service Started.
08-11 08:16:17.765 8724-8818/ut.app W/PluginManager: THREAD WARNING: exec() call to PayTM.startPayment blocked the main thread for 52ms. Plugin should use CordovaInterface.getThreadPool().
08-11 08:16:17.785 8724-8735/ut.app I/zygote: NativeAlloc concurrent copying GC freed 8(32KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 1702KB/3MB, paused 9.809ms total 83.530ms
08-11 08:16:17.786 8724-8724/ut.app W/zygote: Attempt to remove non-JNI local reference, dumping thread
08-11 08:16:17.794 8724-8724/ut.app D/CordovaActivity: Paused the activity.
08-11 08:16:17.841 8724-8724/ut.app W/zygote: Attempt to remove non-JNI local reference, dumping thread
08-11 08:16:17.856 8724-8724/ut.app D/PGSDK: Hide Header false
    Initializing the UI of Transaction Page...
08-11 08:16:17.932 8724-8724/ut.app D/PGSDK: Initialized UI of Transaction Page.
    Starting the Process...
08-11 08:16:17.933 8724-8724/ut.app D/PGSDK: Starting the Client Authentication...
    Extracting Strings from Bundle...
08-11 08:16:17.938 8724-8724/ut.app D/PGSDK: URL encoded String is INDUSTRY_TYPE_ID=Retail&CHANNEL_ID=WAP&MOBILE_NO=7777777777&REQUEST_TYPE=DEFAULT&TXN_AMOUNT=2497.80&MID=dgqr%40CJD0%40UBhkWZ&EMAIL=raju%40sibaecom.com&CALLBACK_URL=https%3A%2F%2Fsecuregw.paytm.in%2Ftheia%2FpaytmCallback%3FORDER_ID%3DUT8153LQ6407_ea2746da-e17d-4e8c-beb0-87cb7a22c467&CUST_ID=4567fghhn&WEBSITE=APPSTAGING&ORDER_ID=UT8153LQ6407_ea2746da-e17d-4e8c-beb0-87cb7a22c467
08-11 08:16:17.959 8724-8800/ut.app D/EGL_emulation: eglMakeCurrent: 0xd150a960: ver 2 0 (tinfo 0xd34765a0)
08-11 08:16:18.204 8724-8724/ut.app W/zygote: Attempt to remove non-JNI local reference, dumping thread
08-11 08:16:18.292 8724-8724/ut.app W/zygote: Attempt to remove non-JNI local reference, dumping thread
08-11 08:16:18.311 8724-8788/ut.app D/EGL_emulation: eglMakeCurrent: 0xe9687a00: ver 2 0 (tinfo 0xd3b1b870)
08-11 08:16:18.406 8724-8724/ut.app W/zygote: Attempt to remove non-JNI local reference, dumping thread
08-11 08:16:18.442 8724-8788/ut.app D/EGL_emulation: eglMakeCurrent: 0xe9687a00: ver 2 0 (tinfo 0xd3b1b870)
08-11 08:16:18.456 8724-8724/ut.app D/PGSDK: Page started loading https://pguat.paytm.com/oltp-web/processTransaction?ORDER_ID=UT8153LQ6407_ea2746da-e17d-4e8c-beb0-87cb7a22c467
    Progress dialog started
08-11 08:16:18.484 8724-8788/ut.app D/EGL_emulation: eglMakeCurrent: 0xe9687a00: ver 2 0 (tinfo 0xd3b1b870)
08-11 08:16:18.546 8724-8724/ut.app W/zygote: Attempt to remove non-JNI local reference, dumping thread
08-11 08:16:19.945 8724-8724/ut.app I/chatty: uid=10080(ut.app) identical 31 lines
08-11 08:16:20.016 8724-8724/ut.app W/zygote: Attempt to remove non-JNI local reference, dumping thread
08-11 08:16:20.085 8724-8724/ut.app D/CordovaActivity: Stopped the activity.
08-11 08:16:22.835 8724-8724/ut.app W/zygote: Attempt to remove non-JNI local reference, dumping thread




Has my authentication failed?

**Comment by ArunYogi** [comment]
Callback url for staging is different from production:
staging: https://pguat.paytm.com/paytmchecksum/paytmCallback.jsp
production:https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=<ORDER_ID>

Is MID correct one? Doesn't seems to follow Paytm's pattern.
Check the rules for ORDER_ID as well, I am not sure, whether "_" is allowed in it or not.

Further more, Paytm team is the correct entity to address your problem.

**Comment by UTSOURCE** [comment]
@ArunYogi Okay thank you! I am checking these places, thank you very much.

**Comment by UTSOURCE** [comment]
@ArunYogi  Returned to me in the background   MID="UTSOUR42566254131921"


adb logac:
![image](https://user-images.githubusercontent.com/14830459/43989890-3eccf0a6-9d85-11e8-8132-c8d3fbca39cc.png)


This is wrong.

my cmd cll ：
cordova plugin add cordova-plugin-paytm --variable MERCHANT_ID="dgqr@CJD0@UBhkWZ" --variable INDUSTRY_TYPE_ID="Retail" --variable WEBSITE="APPSTAGING" --save

MERCHANT_ID="dgqr@CJD0@UBhkWZ"

Is it wrong with me?

**Comment by ArunYogi** [comment]
MID is the MERCHANT_ID. 
Its clear your MID/MERCHANT_ID is `UTSOUR42566254131921` not "dgqr@CJD0@UBhkWZ". I don't know from where you got this `dgqr@CJD0@UBhkWZ`. Try with `UTSOUR42566254131921`. you need to remove and add the plugin with new MID..

**Comment by UTSOURCE** [comment]
@ArunYogi I tried, but I still couldn't do it.
paytm Developer Center， I can't get in because I'm abroad. I wonder if the web settings are different from the app settings in the originator.


![image](https://user-images.githubusercontent.com/14830459/43998878-f1adbf04-9e32-11e8-8624-1343d6a98c45.png)



Web can use this way to jump to paytm payment.

**Comment by ArunYogi** [comment]
Paytm will give you different account/credential for WEB and different one for WAP. Handling method is also different for WEB and WAP.
If you are using WEB credential with this plugin, Paytm is the only entity can comment on the behaviour of app.

**Comment by UTSOURCE** [comment]
@ArunYogi When I do not add "ENVIRONMENT": "staging", I report the wrong Network Not Available:501.

If added, it will report oops.
![image](https://user-images.githubusercontent.com/14830459/44010854-902f9652-9ee7-11e8-9855-b1e3c45e3a67.png)

**Comment by UTSOURCE** [comment]
@ArunYogi I'm sorry to disturb you for so long. My account is not registered.
Mobile payments at your store
![image](https://user-images.githubusercontent.com/14830459/44028751-83b94c38-9f2d-11e8-8e5e-c612691c3f00.png)
That should be the reason.

I'm very sorry.
